# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: messagebird 0.1.4 ruby lib

Gem::Specification.new do |s|
  s.name = "messagebird"
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Bram de Vries"]
  s.date = "2014-02-11"
  s.description = "Implementation of the MessageBird SMS API for Ruby"
  s.email = "dev@blaet.net"
  s.executables = ["messagebird_test_connection"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "CHANGES.md",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/messagebird_test_connection",
    "lib/messagebird.rb",
    "lib/messagebird/config.rb",
    "lib/messagebird/deliverable.rb",
    "lib/messagebird/helpers.rb",
    "lib/messagebird/http/local_connection.rb",
    "lib/messagebird/http/response.rb",
    "lib/messagebird/http/response_code.rb",
    "lib/messagebird/http/sender.rb",
    "lib/messagebird/http/sms.rb",
    "lib/messagebird/sms.rb",
    "messagebird.gemspec",
    "test/helper.rb",
    "test/messagebird/config_test.rb",
    "test/messagebird/deliverable_test.rb",
    "test/messagebird/helpers_test.rb",
    "test/messagebird/http/local_connection_test.rb",
    "test/messagebird/http/response_code_test.rb",
    "test/messagebird/http/response_test.rb",
    "test/messagebird/http/sender_test.rb",
    "test/messagebird/http/sms_test.rb",
    "test/messagebird/sms_test.rb",
    "test/messagebird_test.rb"
  ]
  s.homepage = "http://github.com/blaet/messagebird-sms-api-ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.0"
  s.summary = "MessageBird API for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0.0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0.0"])
  end
end

